<template>
<div>
    <b-form class="my-3 mx-2">
                <b-form-input class="text-center" type="text" placeholder="Buscar contacto">
                </b-form-input>
    </b-form>
    <b-list-group>
                <contacto-componente color="dark">
                </contacto-componente>

                <contacto-componente color="">
                </contacto-componente>

                <contacto-componente color="primary">
                </contacto-componente>
    </b-list-group>
</div>
</template>
<script>
    
</script>
